spring.application.name=eventos

spring.datasource.url=jdbc:postgresql://localhost:5432/eventos_db
spring.datasource.username=postgres
spring.datasource.password=Jv374315.

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

server.port=8081